# Generated by Django 5.0.1 on 2025-04-18 11:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admin_panel", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Plugin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                (
                    "key",
                    models.CharField(max_length=100, unique=True, verbose_name="Ключ"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "settings",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Настройки"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлен"),
                ),
            ],
            options={
                "verbose_name": "Плагин",
                "verbose_name_plural": "Плагины",
                "ordering": ["name"],
            },
        ),
    ]
