# Generated by Django 5.0.1 on 2025-04-18 12:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admin_panel", "0002_plugin"),
    ]

    operations = [
        migrations.CreateModel(
            name="BankAPI",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Название банка"),
                ),
                ("api_key", models.CharField(max_length=255, verbose_name="API ключ")),
                (
                    "api_secret",
                    models.CharField(max_length=255, verbose_name="API секрет"),
                ),
                ("base_url", models.URLField(verbose_name="Базовый URL")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "webhook_url",
                    models.URLField(blank=True, verbose_name="Webhook URL"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлен"),
                ),
            ],
            options={
                "verbose_name": "API Банка",
                "verbose_name_plural": "API Банков",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="apiendpoint",
            name="bank_api",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="admin_panel.bankapi",
                verbose_name="API Банка",
            ),
        ),
        migrations.AddField(
            model_name="transactionlog",
            name="bank_api",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="admin_panel.bankapi",
                verbose_name="API Банка",
            ),
        ),
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "card_number",
                    models.CharField(
                        max_length=16,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\d{16}$", "Номер карты должен содержать 16 цифр"
                            )
                        ],
                        verbose_name="Номер карты",
                    ),
                ),
                (
                    "cardholder_name",
                    models.CharField(max_length=100, verbose_name="Имя держателя"),
                ),
                (
                    "expiry_month",
                    models.CharField(
                        max_length=2,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\d{2}$", "Месяц должен содержать 2 цифры"
                            )
                        ],
                        verbose_name="Месяц",
                    ),
                ),
                (
                    "expiry_year",
                    models.CharField(
                        max_length=2,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\d{2}$", "Год должен содержать 2 цифры"
                            )
                        ],
                        verbose_name="Год",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активна"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создана"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлена"),
                ),
                (
                    "bank",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="admin_panel.bankapi",
                        verbose_name="Банк",
                    ),
                ),
            ],
            options={
                "verbose_name": "Карта",
                "verbose_name_plural": "Карты",
                "ordering": ["-created_at"],
            },
        ),
    ]
